<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>2.13.3</Version>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>PostHog</PackageId>
        <Description>A library for interacting with the PostHog Analytics Platform.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1' or '$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="System.Threading.Channels" />
        <PackageReference Include="System.Net.Http.Json" />
        <PackageReference Include="Microsoft.Bcl.TimeProvider" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="Microsoft.Bcl.HashCode" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
        <None Include="../package-icon.png" Link="package-icon.png" Pack="true" PackagePath="\package-icon.png" />
    </ItemGroup>

    <Target Name="GenerateVersionConstants" BeforeTargets="BeforeBuild">
        <ReadLinesFromFile File="BuildInfo/VersionConstantsTemplate.txt">
            <Output TaskParameter="Lines" ItemName="TemplateLines" />
        </ReadLinesFromFile>
        <WriteLinesToFile
                File="Generated/VersionConstants.cs"
                Lines="/*&#10;   GENERATED FILE! Do not directly modify this file.&#10;   This is generated by an MSBuild task in PostHog.csproj&#10;*/&#10;&#10;namespace PostHog.Versioning%3B&#10;&#10;/// &lt;summary&gt;&#10;/// Provides the SDK version generated from the package version.&#10;/// &lt;/summary&gt;&#10;public static class VersionConstants&#10;{&#10;    /// &lt;summary&gt;&#10;    /// The version of the PostHog package.&#10;    /// &lt;/summary&gt;&#10;    public const string Version = &quot;$(Version)&quot;%3B&#10;}&#10;"
                Overwrite="true" />
    </Target>
</Project>
